services:
  - type: web
    name: google-trend-treemap
    env: python
    plan: free
    region: singapore
    buildCommand: |
      pip install -r requirements.txt
      python -m playwright install chromium
    startCommand: python api.py
